apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: y6rurtu7f-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-nodejs:github-db4c696cdb0d427c0a5e556602ec06d95705adab
          name: container-image
